/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Secure.View_Patient;
import Secure.Welcome;

/**
 *
 * @author User
 */
public class Admin_Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Welcome
     */
    public Admin_Welcome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Emp_Registration = new javax.swing.JButton();
        Attendence = new javax.swing.JButton();
        WardManagment = new javax.swing.JButton();
        ViewPatient = new javax.swing.JButton();
        Manage_Users = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Welcome Page");
        setMinimumSize(new java.awt.Dimension(1000, 665));

        jPanel1.setMinimumSize(new java.awt.Dimension(1364, 730));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Welcome Admin..");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 220, 20));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(102, 153, 255));

        Emp_Registration.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Emp_Registration.setForeground(new java.awt.Color(0, 102, 255));
        Emp_Registration.setText("Employee Registration");
        Emp_Registration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Emp_Registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_RegistrationActionPerformed(evt);
            }
        });

        Attendence.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Attendence.setForeground(new java.awt.Color(0, 102, 255));
        Attendence.setText("Attendence");
        Attendence.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendenceActionPerformed(evt);
            }
        });

        WardManagment.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        WardManagment.setForeground(new java.awt.Color(0, 102, 255));
        WardManagment.setText("Ward Managment");
        WardManagment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WardManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WardManagmentActionPerformed(evt);
            }
        });

        ViewPatient.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ViewPatient.setForeground(new java.awt.Color(0, 102, 255));
        ViewPatient.setText("View Patient");
        ViewPatient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPatientActionPerformed(evt);
            }
        });

        Manage_Users.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Manage_Users.setForeground(new java.awt.Color(0, 102, 255));
        Manage_Users.setText("Manage Users");
        Manage_Users.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Manage_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_UsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WardManagment, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(ViewPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Manage_Users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Attendence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Emp_Registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Emp_Registration)
                .addGap(29, 29, 29)
                .addComponent(Attendence)
                .addGap(31, 31, 31)
                .addComponent(Manage_Users)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(WardManagment)
                .addGap(18, 18, 18)
                .addComponent(ViewPatient)
                .addGap(114, 114, 114))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 480));

        jbtnLogout.setBackground(new java.awt.Color(51, 102, 255));
        jbtnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gnome_panel_force_quit.png"))); // NOI18N
        jbtnLogout.setText("LOG OUT");
        jbtnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/all.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WardManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WardManagmentActionPerformed
        Ward_Management wm = new Ward_Management();
        wm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_WardManagmentActionPerformed

    private void Emp_RegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_RegistrationActionPerformed
        Select_EmployeeRegistration new_emp = new  Select_EmployeeRegistration();   //Load the SelectEmployee interface and hide this interface
        new_emp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Emp_RegistrationActionPerformed

    private void Manage_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_UsersActionPerformed
        User_Management um = new User_Management();                                 //Load the UserManagment interface and hide this interface
        um.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Manage_UsersActionPerformed

    private void ViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPatientActionPerformed
        View_Patient vp = new View_Patient();                                       //Load the View_Patient interface and hide this interface
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewPatientActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        Welcome welcome = new  Welcome();
        welcome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void AttendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendenceActionPerformed
       View_Attendence attendence = new View_Attendence();
       attendence.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_AttendenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attendence;
    private javax.swing.JButton Emp_Registration;
    private javax.swing.JButton Manage_Users;
    private javax.swing.JButton ViewPatient;
    private javax.swing.JButton WardManagment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnLogout;
    // End of variables declaration//GEN-END:variables
}
