/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reception;

import Reception.Reception_Welcome;
import Secure.DBConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Attendence extends javax.swing.JFrame {
    int count=0;
    String exists="no";
    /**
     * Creates new form Attendence
     */
    public Attendence() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jEmpId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox();
        jGetDetails = new javax.swing.JButton();
        jbtnIncrement = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDays = new javax.swing.JTextField();
        jbtnDecrement = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attendence");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Employee Id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel1.add(jEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employee Name", "Type"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 430, 240));

        jLabel3.setText("Month :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, -1));

        jGetDetails.setText("Get Details");
        jGetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(jGetDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jbtnIncrement.setText("Increment");
        jbtnIncrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIncrementActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIncrement, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 120, -1));

        jLabel4.setText("No of Days : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        jPanel1.add(txtDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, -1));

        jbtnDecrement.setText("Decrement");
        jbtnDecrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecrementActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDecrement, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 120, -1));

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 120, -1));

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 120, -1));

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 120, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/all.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGetDetailsActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            ResultSet rs1 = stat.executeQuery("SELECT Fname,Lname,Type FROM employees WHERE employees.Employee_ID='" + jEmpId.getText() + "'" );
            
            boolean type=false;
            DefaultTableModel DataModel = (DefaultTableModel)jTable1.getModel();
            DataModel.setRowCount(0);
            while(rs1.next()) {
                
                String  Name=rs1.getString("Fname")+ " " +rs1.getString("Lname");
                //String Type=rs1.getString(3);
                 
                DataModel.addRow(new Object[]{Name,rs1.getString(3)});
                type=true;
            
            }
            if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning!Invalid Employee No","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
            }
         catch (SQLException ex) {
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jGetDetailsActionPerformed

    private void jbtnIncrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIncrementActionPerformed
        if(cmbMonth.getSelectedItem()=="Select"){
            JOptionPane.showMessageDialog(this,"Select a valid Month","Unsuccess!",JOptionPane.INFORMATION_MESSAGE); 
        }
        else{
        ++count;
        txtDays.setText(Integer.toString(count));
    }//GEN-LAST:event_jbtnIncrementActionPerformed
    }
    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        
        try {
            Statement stat= DBConnect.getStatemennt();
            ResultSet rs = stat.executeQuery( "SELECT "+cmbMonth.getSelectedItem().toString()+" FROM attendence WHERE Emp_Id='"
                    + jEmpId.getText()+"'") ;
            
            if (rs.next()){
                count = Integer.parseInt(rs.getString(1));
                exists="yes";
            }
            txtDays.setText(Integer.toString(count));
            
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_cmbMonthActionPerformed

    private void jbtnDecrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecrementActionPerformed
        if(cmbMonth.getSelectedItem()=="Select"){
            JOptionPane.showMessageDialog(this,"Select a valid Month","Unsuccess!",JOptionPane.INFORMATION_MESSAGE); 
        }
        else if (count==0){
            JOptionPane.showMessageDialog( this, "Cannot Decrement Further","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
        --count;
        txtDays.setText(Integer.toString(count));
        }
    }//GEN-LAST:event_jbtnDecrementActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        if(cmbMonth.getSelectedItem()=="Select"){
            JOptionPane.showMessageDialog(this,"Select a valid Month","Unsuccess!",JOptionPane.INFORMATION_MESSAGE); 
        }
        try {
        Statement stat= DBConnect.getStatemennt();
        if (exists.equals("yes")){
            
                stat.executeUpdate("UPDATE attendence SET "+cmbMonth.getSelectedItem().toString()+"='"+Integer.toString(count)+"' WHERE attendence.Emp_Id='"
                    + jEmpId.getText()+"'") ;;
             
    }//GEN-LAST:event_jbtnUpdateActionPerformed
        else{
                stat.executeUpdate("INSERT INTO attendence(Emp_Id,"+cmbMonth.getSelectedItem().toString()+") "
                        + "VALUES ('"+ jEmpId.getText()+"','"+ txtDays.getText()+"')");
                 }
        JOptionPane.showMessageDialog(this,"Successfully Updated","Sucess",JOptionPane.INFORMATION_MESSAGE);
        }
    catch (SQLException ex) {
                Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    }
    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
                   jEmpId.setText(null);
                //cmbMonth.setSelectedItem.equals();
                txtDays.setText("");
                //jTable1.setModel(null);
               // jTable1.setRowCount(0);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
       Reception_Welcome rec_welcome = new Reception_Welcome();
       rec_welcome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnBackActionPerformed
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JTextField jEmpId;
    private javax.swing.JButton jGetDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDecrement;
    private javax.swing.JButton jbtnIncrement;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField txtDays;
    // End of variables declaration//GEN-END:variables
}
