/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reception;

import Secure.DBConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Calculate_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Calculate_Bill
     */
    public Calculate_Bill() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Patient_Id = new javax.swing.JTextField();
        jbtnGetdetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnCal_Bill = new javax.swing.JButton();
        jtxtbill = new javax.swing.JTextField();
        jbtnReset = new javax.swing.JButton();
        payment = new javax.swing.JTextField();
        jbtnBalance = new javax.swing.JButton();
        jtxtbalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtReception_Id = new javax.swing.JTextField();
        jbtnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtBill_No = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Id :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        jPanel1.add(Patient_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));

        jbtnGetdetails.setText("Get Details");
        jbtnGetdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGetdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGetdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patien_Name", "Test_Name", "Test Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 450, 210));

        jbtnCal_Bill.setText("Bill");
        jbtnCal_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCal_BillActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCal_Bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 80, -1));

        jtxtbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbillActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 220, -1));

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, -1));
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 220, -1));

        jbtnBalance.setText("Balance");
        jbtnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 80, -1));
        jPanel1.add(jtxtbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 220, -1));

        jLabel2.setText("Receptin Id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        jPanel1.add(jtxtReception_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 140, -1));

        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 100, -1));

        jLabel3.setText("Payment :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jLabel4.setText("Bill_No :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
        jPanel1.add(jtxtBill_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public double count=0;
public double bill=0;
    private void jbtnGetdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGetdetailsActionPerformed
        String pati_id=Patient_Id.getText();
        if(pati_id.isEmpty())
      {
            JOptionPane.showMessageDialog(this,"Patient Id field is Empty","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
      }
        else{  
            try {
            Statement statone= DBConnect.getStatemennt();
            Statement stattwo= DBConnect.getStatemennt();
            ResultSet rs1 = statone.executeQuery("SELECT test_results.Patient_name,test_results.Test_Category FROM test_results WHERE test_results.Patient_Id='" +Patient_Id.getText() + "'" );
             ResultSet rs2 = stattwo.executeQuery("SELECT test.Price FROM test,test_results WHERE test_results.Testcategory_id=test.Testcategory_id");
            boolean type=false;
            DefaultTableModel DataModel = (DefaultTableModel)jTable1.getModel();
            DataModel.setRowCount(0);
            
            
            while(rs1.next()& rs2.next())
            {
                DataModel.addRow(new Object[]{rs1.getString(1),rs1.getString(2),rs2.getInt(1)});
                type=true;
                count=count+rs2.getInt(1);
            
            }
            if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning!Invalid Patient_Id","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
            
            } catch (SQLException ex) {
            Logger.getLogger(Calculate_Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jbtnGetdetailsActionPerformed

    private void jbtnCal_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCal_BillActionPerformed
        int standered_value = 1500;
        bill=count+standered_value;
        String strbill = Float.toString((float) bill);
        jtxtbill.setText(strbill);
        
    }//GEN-LAST:event_jbtnCal_BillActionPerformed

    private void jtxtbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbillActionPerformed
        
    }//GEN-LAST:event_jtxtbillActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       Patient_Id.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBalanceActionPerformed
        String pay = payment.getText();
        float payment = Float.parseFloat(pay);
        float Balance = (payment-(float)bill);
        String fin_Balance = Float.toString((float) Balance);
        jtxtbalance.setText(fin_Balance);
        
        
    }//GEN-LAST:event_jbtnBalanceActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            stat.executeUpdate("INSERT INTO bill(Bill_No,Reception_Id,Patient_Id,Bill) VALUES('"+jtxtBill_No.getText()+"','"+jtxtReception_Id.getText()+"','"+Patient_Id.getText()+"','"+jtxtbill.getText()+"')");
        } catch (SQLException ex) {
            Logger.getLogger(Calculate_Bill.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculate_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculate_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Patient_Id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnBalance;
    private javax.swing.JButton jbtnCal_Bill;
    private javax.swing.JButton jbtnGetdetails;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtBill_No;
    private javax.swing.JTextField jtxtReception_Id;
    private javax.swing.JTextField jtxtbalance;
    private javax.swing.JTextField jtxtbill;
    private javax.swing.JTextField payment;
    // End of variables declaration//GEN-END:variables
}
