package Doctor;
import Secure.DBConnect;
import Admin.Select_EmployeeRegistration;
import Admin.Ward_Management;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Doctor_Registration extends javax.swing.JFrame {
    
    /**
     * Creates new form Admin
     */
    public Doctor_Registration() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jFname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLname = new javax.swing.JTextField();
        jdob = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jdatejoined = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTitle = new javax.swing.JComboBox();
        jmartialst = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jContactno = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jBranch = new javax.swing.JTextField();
        jBank = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jex = new javax.swing.JTextField();
        jspecial = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jStatus = new javax.swing.JComboBox();
        jAdd = new javax.swing.JButton();
        getdata = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jdoctorId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDep = new javax.swing.JComboBox();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1001, 735));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1001, 735));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Personal Details");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));
        jPanel6.add(jFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 188, 230, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Title :");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("First Name :");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Last Name :");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 230, -1, -1));
        jPanel6.add(jLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 228, 230, -1));
        jPanel6.add(jdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 268, 230, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("DOB :");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 270, -1, -1));
        jPanel6.add(jdatejoined, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 391, 230, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Gender :");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 311, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Martial Status :");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 353, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Date Joined : ");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 396, -1, -1));

        jTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr", "Mrs", "Miss" }));
        jPanel6.add(jTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 148, -1, -1));

        jmartialst.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Married", "UnMarried" }));
        jPanel6.add(jmartialst, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 351, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Contact Details");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Address :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Contact No :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jAddress)
                            .addComponent(jContactno, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jContactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 466, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Bank Details");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Branch :");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Bank Name : ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBank)
                            .addComponent(jBranch, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 466, -1, 227));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Qualification");

        jLabel35.setText("Experienced Years :");

        jLabel1.setText("Specialized Area :");

        jspecial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Null", "Allergology", "Anesthesiology", "Cardiology", "Dermatology", "Emergency Medicine ", "Family and General Practice", "Gastroenterology", "Internal Medicine", "Obstetrics & Gynecology", "Orthopedics ", "Pathology", "Pediatrics", "Psychiatry", "Radiology", "Surgery", "Research", "Public Health" }));

        jLabel5.setText("Status :");

        jStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consultant", "Specialist", "General" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jex)
                    .addComponent(jspecial, 0, 155, Short.MAX_VALUE)
                    .addComponent(jStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 53, 350, 400));

        jAdd.setText("Add");
        jAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });
        jPanel6.add(jAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 132, -1));

        getdata.setText("Get Data");
        getdata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdataActionPerformed(evt);
            }
        });
        jPanel6.add(getdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 132, -1));

        jDelete.setText("Delete");
        jDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        jPanel6.add(jDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 132, -1));

        jBack.setText("Back");
        jBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        jPanel6.add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 132, -1));

        jLabel2.setText("Doctor Id :");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 56, -1, -1));
        jPanel6.add(jdoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 53, 230, -1));

        jLabel4.setText("Department :");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 429, 85, -1));

        jDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OPD", "LAB", "Maternity", "Pediatrics", "Oncology", "Gynecologist" }));
        jPanel6.add(jDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 426, 230, -1));

        buttonGroup1.add(female);
        female.setText("Female");
        jPanel6.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 308, -1, -1));

        buttonGroup1.add(male);
        male.setText("Male");
        jPanel6.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 308, -1, -1));

        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel6.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 130, -1));

        update.setText("Update");
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel6.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 130, -1));

        jLabel3.setText("Type : ");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));

        jType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Doctor", "Admin", "Receptionist", "Lab Assistant", "Maintenance" }));
        jType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypeActionPerformed(evt);
            }
        });
        jPanel6.add(jType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, -1));

        jTabbedPane2.addTab("Doctor", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            String gender = "";
           


                if (male.isSelected()) {
                    gender = "Male";
                } else if (female.isSelected()) {
                    gender = "Female";
                }
            
            
            
           stat.executeUpdate("INSERT INTO doctor(Doctor_Id,Experienced_Years,Specialised_Area,Status) VALUES('"+jdoctorId.getText()+"','"+jex.getText()+"','"+jspecial.getSelectedItem()+"','"+jStatus.getSelectedItem()+"')");

           
             
            stat.executeUpdate("INSERT INTO employees(Employee_ID,Type,Title,Fname,Lname,DOB,Gender,Martial_Status,Date_Joined,Department,Address,Contact_No,Bank_name,Branch) VALUES('"+jdoctorId.getText()+"','"+jType.getSelectedItem()+"','"+jTitle.getSelectedItem()+"','"+jFname.getText()+"','"+jLname.getText()+"','"+jdob.getText()+"','"+ gender +"','"+jmartialst.getSelectedItem()+"','"+jdatejoined.getText()+"','"+jDep.getSelectedItem()+"','"+jAddress.getText()+"','"+jContactno.getText()+"','"+jBank.getText()+"','"+jBranch.getText()+"')");

            
             
        }
        catch (Exception ex) {
           ex.printStackTrace();
            
        }
             
          
        
          
             
             
             
    }//GEN-LAST:event_jAddActionPerformed
public String doc_id;
    private void getdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdataActionPerformed
       try {
            Statement stat= DBConnect.getStatemennt();
             ResultSet rs = stat.executeQuery("select employees.Employee_ID,employees.Type,employees.Title,employees.Fname,employees.Lname,employees.DOB,employees.Gender,employees.Martial_Status,employees.Date_Joined,employees.Department,employees.Address,employees.Contact_No,employees.Bank_name,employees.Branch,doctor.Experienced_Years,doctor.Specialised_Area,doctor.Status from employees,doctor where employees.Employee_ID=doctor.Doctor_Id");
           //JOptionPane.showMessageDialog(this, "asdfdf", "sdfasd", 0);
           boolean type=false;
           while(rs.next())
            {
                String doc_id=rs.getString(1);
                String Type=rs.getString(2);
                String title = rs.getString(3);
                String Fname=rs.getString(4);
                String Lname=rs.getString(5);
                String DOB=rs.getString(6);
                String gender=rs.getString(7);
                String Martial_Status=rs.getString(8);
                String Date_Joined=rs.getString(9);
                String Department=rs.getString(10);
                String Address=rs.getString(11);
                String Contact_No=rs.getString(12);
                String Bank=rs.getString(13);
                String Branch=rs.getString(14);
                String experiencedyears=rs.getString(15);
                String speciality=rs.getString(16);
                String Status=rs.getString(17);
                
               
               System.out.println(Fname);
               System.out.println(Lname);
               
               if(doc_id.equals(jdoctorId.getText())) 
               {
                   type = true;
                jTitle.setSelectedItem(title);
                jType.setSelectedItem(Type);
                jFname.setText(Fname);
                jLname.setText(Lname);
                jdob.setText(DOB);
                
                jmartialst.setSelectedItem(Martial_Status);
                jdatejoined.setText(Date_Joined);
                jDep.setSelectedItem(Department);
                jAddress.setText(Address);
                jContactno.setText(Contact_No);
                jex.setText(experiencedyears);
                jspecial.setSelectedItem(speciality);
                jStatus.setSelectedItem(Status);
                jBank.setText(Bank);
                jBranch.setText(Branch);
                if (gender.equals("Female"))
                        {
                            female.setSelected(true);
                        }
                else
                    {
                            male.setSelected(true);
                    }
               }
              
            }
            
            
                 
                
                    
            
             
                
                    
              
            if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning!There is no any Employee in that No!","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
       } 
             catch (SQLException ex) {
                    Logger.getLogger(Doctor_Registration.class.getName()).log(Level.SEVERE, null, ex);
                }
            
             
             
          
            
    }//GEN-LAST:event_getdataActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        if(jdoctorId.getText().equals(""))
      {
            JOptionPane.showMessageDialog(this,"Error! Enter an Employee Id","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
            
      }
      
        try {
            boolean type=false;
            Statement stat= DBConnect.getStatemennt();
            
            
             
            stat.executeUpdate("DELETE FROM doctor where Doctor_Id='" + jdoctorId.getText() + "'");
            stat.executeUpdate("DELETE FROM employees where Employee_ID='" + jdoctorId.getText() + "'");
            JOptionPane.showMessageDialog(this,"Successfilly Deleted!","success!",JOptionPane.INFORMATION_MESSAGE); 
            type=true;
            
         if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning!There is no any Employee in that No!","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
                     
        } catch (SQLException ex) {
            Logger.getLogger(Ward_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        Select_EmployeeRegistration aw = new Select_EmployeeRegistration();
        aw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBackActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
                jTitle.setSelectedItem(null);
                jType.setSelectedItem("Select");
                jFname.setText(null);
                jLname.setText(null);
                jdob.setText(null);
                jmartialst.setSelectedItem(null);
                jdatejoined.setText(null);
                jDep.setSelectedItem(null);
                jAddress.setText(null);
                jContactno.setText(null);
                jex.setText(null);
                jspecial.setSelectedItem(null);
                jStatus.setSelectedItem(null);
                jBank.setText(null);
                jBranch.setText(null);
    }//GEN-LAST:event_resetActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            
            stat.executeUpdate("UPDATE doctor set Experienced_Years='"+jex.getText()+"',Specialised_Area='"+jspecial.getSelectedItem()+"',Status='"+jStatus.getSelectedItem()+"' where Doctor_Id='" + jdoctorId.getText() + "'" );
            
            stat.executeUpdate("UPDATE employees set Title='"+jTitle.getSelectedItem()+"',Type='"+jType.getSelectedItem()+"',Fname='"+jFname.getText()+"',Lname='"+jLname.getText()+"',DOB='"+jdob.getText()+"',Martial_Status='"+jmartialst.getSelectedItem()+"',Date_Joined='"+jdatejoined.getText()+"',Department='"+jDep.getSelectedItem()+"',Address='"+jAddress.getText()+"',Contact_No='"+jContactno.getText()+"' where Employee_ID='" + jdoctorId.getText() + "'" );
            JOptionPane.showMessageDialog(this,"Successfilly Updateed!","success!",JOptionPane.INFORMATION_MESSAGE); 
            
        } catch (SQLException ex) {
            Logger.getLogger(Doctor_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
    }//GEN-LAST:event_updateActionPerformed

    private void jTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTypeActionPerformed
        
        
        
        
        
        
        
    
    /**}
     *} @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton getdata;
    private javax.swing.JButton jAdd;
    private javax.swing.JTextField jAddress;
    private javax.swing.JButton jBack;
    private javax.swing.JTextField jBank;
    private javax.swing.JTextField jBranch;
    private javax.swing.JTextField jContactno;
    private javax.swing.JButton jDelete;
    private javax.swing.JComboBox jDep;
    private javax.swing.JTextField jFname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLname;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox jStatus;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox jTitle;
    private javax.swing.JComboBox jType;
    private javax.swing.JTextField jdatejoined;
    private javax.swing.JTextField jdob;
    private javax.swing.JTextField jdoctorId;
    private javax.swing.JTextField jex;
    private javax.swing.JComboBox jmartialst;
    private javax.swing.JComboBox jspecial;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton reset;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
