/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import Secure.DBConnect;
import Secure.DBConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Doctor_SearchPatient extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_SearchPatient
     */
    public Doctor_SearchPatient() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPa_Id = new javax.swing.JTextField();
        jPaName = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        Contactno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Wardid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSearch = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient_Id :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 41, -1, -1));

        jLabel2.setText("Patient Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 88, -1, -1));

        jLabel3.setText("DOB :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 129, -1, -1));

        jLabel4.setText("Contact No :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 176, -1, -1));
        getContentPane().add(jPa_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 38, 141, -1));
        getContentPane().add(jPaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 85, 141, -1));

        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 126, 141, -1));
        getContentPane().add(Contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 173, 141, -1));

        jLabel5.setText("Ward_Id :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 41, -1, -1));
        getContentPane().add(Wardid, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 38, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Test ID", "Test Name", "Test Results", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 774, 184));

        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 534, 127, -1));

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 628, 127, -1));

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 577, 127, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/all.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        if(jPa_Id.getText().equals(""))
      {
            JOptionPane.showMessageDialog(this,"Error! Empty Patient Id field","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
            
      }
        try {
            Statement stat= DBConnect.getStatemennt();
            ResultSet rs1 = stat.executeQuery("SELECT 	Patient_Id,First_name,Last_name,DOB,Contact_No,Ward_id FROM patient_details WHERE Patient_Id='" + jPa_Id.getText() + "'" );
            
            boolean type=false;
            while(rs1.next()) {
                String paid = rs1.getString(1);
                String  Name=rs1.getString("First_name")+ " " +rs1.getString("Last_name");
                String dob=rs1.getString(4);
                String contact_no=rs1.getString(5);
                String ward_id=rs1.getString(6);
                
                System.out.println(paid);
                System.out.println(Name);
                System.out.println(dob);
                System.out.println(contact_no);
                System.out.println(ward_id);
                
               
                
               if(paid.equals(jPa_Id.getText())) 
               {
                   type = true;
                jPaName.setText(Name);
                DOB.setText(dob);
                Contactno.setText(contact_no);
                Wardid.setText(ward_id);
               }
              
            }
            if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning!There is no any patient in that Number!","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
            
                 
            
            
            ResultSet rs2 = stat.executeQuery("SELECT Testid,Test_Category,Description,Date FROM test_results "
                    + "WHERE Patient_Id LIKE '%"+jPa_Id.getText()+"%' ");
            
            DefaultTableModel registrationModel = (DefaultTableModel)jTable1.getModel();
            registrationModel.setRowCount(0);
            while(rs2.next())
            {
                registrationModel.addRow(new Object[]{rs2.getString(1),rs2.getString(2),rs2.getString(3),rs2.getString(4)});
            }
            
            
            
        }   
            
            
         catch (SQLException ex) {
            Logger.getLogger(Doctor_SearchPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
       
       
    }//GEN-LAST:event_jSearchActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        Doctor_Welcome doctor_welcomepage = new Doctor_Welcome();
        doctor_welcomepage.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jPa_Id.setText(null); 
        jPaName.setText(null);
        DOB.setText(null); 
        Contactno.setText(null);
        Wardid.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_SearchPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contactno;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField Wardid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jPaName;
    private javax.swing.JTextField jPa_Id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearch;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnReset;
    // End of variables declaration//GEN-END:variables
}
