/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LabAssistant;
import Secure.DBConnect;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Tests extends javax.swing.JFrame {

    /**
     * Creates new form Tests
     */
    public Tests() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Patientid = new javax.swing.JTextField();
        patientname = new javax.swing.JTextField();
        Labassid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Testid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        testcat = new javax.swing.JComboBox();
        AddTest = new javax.swing.JButton();
        jbtnGetDetails = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTestcatId = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Id :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 40, -1, -1));

        jLabel2.setText("Patient Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 94, -1, -1));

        jLabel3.setText("LabAsstant Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 142, -1, -1));

        Patientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientidActionPerformed(evt);
            }
        });
        getContentPane().add(Patientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 37, 198, -1));
        getContentPane().add(patientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 91, 198, -1));
        getContentPane().add(Labassid, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 139, 198, -1));

        jLabel4.setText("Date :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 194, -1, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 191, 198, -1));

        jLabel5.setText("Test Category :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 151, -1, -1));

        jLabel6.setText("Test Id :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 40, -1, -1));
        getContentPane().add(Testid, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 37, 170, -1));

        jLabel8.setText("Description :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 266, -1, -1));

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 311, 532, 242));

        testcat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blood ", "Urine", "X-ray", "MRI", "Scane" }));
        getContentPane().add(testcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 148, 170, -1));

        AddTest.setText("ADD");
        AddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTestActionPerformed(evt);
            }
        });
        getContentPane().add(AddTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 615, 121, -1));

        jbtnGetDetails.setText("Get Details");
        jbtnGetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGetDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGetDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 572, 121, -1));

        jLabel9.setText("Test Category Id :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 102, -1, -1));

        jTestcatId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Tc1", "Tc2", "Tc3" }));
        getContentPane().add(jTestcatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 99, 170, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/all.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientidActionPerformed

    
                
                
                
                
                
                
    private void AddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTestActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            stat.executeUpdate("INSERT INTO test_results(Testid,Patient_Id,Patient_name,LabAsstant_id,Date,Testcategory_id,Test_Category,Description) VALUES('"+Testid.getText()+"','"+Patientid.getText()+"','"+patientname.getText()+"','"+Labassid.getText()+"','"+date.getText()+"','"+jTestcatId.getSelectedItem()+"','"+testcat.getSelectedItem()+"','"+description.getText()+"')");
            JOptionPane.showMessageDialog(this,"Test Report Issued!","Success!",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Tests.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        Testid.setText(null); 
        Patientid.setText(null);
        patientname.setText(null);
        Labassid.setText(null);
        date.setText(null);
        testcat.setSelectedItem(null);
        description.setText(null);
        
        
    }//GEN-LAST:event_AddTestActionPerformed

    private void jbtnGetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGetDetailsActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            ResultSet rs = stat.executeQuery("select Patient_Id,First_name,Last_name from patient_details where Patient_Id='" + Patientid.getText() + "'");
            
            boolean type=false;
           while(rs.next())
            {
                String pa_Id=rs.getString(1);
                String  patient_name=rs.getString("First_name")+ " " +rs.getString("Last_name");
                
                if(pa_Id.equals(Patientid.getText())) 
               {
                   type = true;
                   patientname.setText(patient_name);
            }
        } 
           if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning!There is no any Patient in that No!","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
       } 
           catch (SQLException ex) {
            Logger.getLogger(Tests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnGetDetailsActionPerformed
            
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTest;
    private javax.swing.JTextField Labassid;
    private javax.swing.JTextField Patientid;
    private javax.swing.JTextField Testid;
    private javax.swing.JTextField date;
    private javax.swing.JTextArea description;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jTestcatId;
    private javax.swing.JButton jbtnGetDetails;
    private javax.swing.JTextField patientname;
    private javax.swing.JComboBox testcat;
    // End of variables declaration//GEN-END:variables
}
