/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Admin.Admin_Welcome;
import Secure.DBConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class User_Management extends javax.swing.JFrame {

    /**
     * Creates new form View_Patient
     */
    public User_Management() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEmpid = new javax.swing.JTextField();
        jUsername = new javax.swing.JTextField();
        jUserType = new javax.swing.JComboBox();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jUserpw = new javax.swing.JPasswordField();
        jbtnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Users");
        setMinimumSize(new java.awt.Dimension(610, 585));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Employee ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel2.setText("User Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 138, -1, -1));

        jLabel3.setText("User Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 209, -1, -1));

        jLabel5.setText("User Type :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        jPanel1.add(jEmpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 180, -1));
        jPanel1.add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 180, -1));

        jUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Doctor", "Receptionist ", "Lab Assistant", " " }));
        jPanel1.add(jUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 180, -1));

        Add.setBackground(new java.awt.Color(204, 204, 204));
        Add.setText("New");
        Add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 461, 120, 40));

        Delete.setBackground(new java.awt.Color(204, 204, 204));
        Delete.setText("Delete");
        Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 461, 110, 40));
        jPanel1.add(jUserpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 180, -1));

        jbtnBack.setBackground(new java.awt.Color(255, 255, 255));
        jbtnBack.setText("Back");
        jbtnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Welcomeback1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
         if(jEmpid.getText().equals(""))
      {
            JOptionPane.showMessageDialog(this,"Error! Enter an Employee Id","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
            
      }
        try {
            boolean condition=false;
            Statement stat= DBConnect.getStatemennt();
            
            stat.executeUpdate("DELETE FROM users WHERE Emp_Id='" + jEmpid.getText() + "'");
            JOptionPane.showMessageDialog(this,"Successfuly Deleted","Success!",JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            Logger.getLogger(User_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if(jEmpid.getText().equals(""))
      {
            JOptionPane.showMessageDialog(this,"Error! Enter an Employee Id","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
            
      }
        if(jUsername.getText().equals(""))
      {
            JOptionPane.showMessageDialog(this,"Error! Enter an Employee Id","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
            
      }if(jUserpw.getText().equals(""))
      {
            JOptionPane.showMessageDialog(this,"Error! Enter an Employee Id","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
            
      }
        try {
            Statement stat= DBConnect.getStatemennt();
            stat.executeUpdate("INSERT INTO users(Emp_Id,user_name,user_passwd,user_type) VALUES('"+jEmpid.getText()+"','"+jUsername.getText()+"','"+jUserpw.getText()+"','"+jUserType.getSelectedItem()+ "')");
            JOptionPane.showMessageDialog(this,"Data Succesfully Entered!","Success!",JOptionPane.INFORMATION_MESSAGE);
            
            jEmpid.setText(null);
            jUsername.setText(null);
            jUserpw.setText(null);
            jUserType.setSelectedItem(null);
        } catch (SQLException ex) {
            Logger.getLogger(User_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        Admin_Welcome admin_welcome = new Admin_Welcome();
        admin_welcome.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jbtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jEmpid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jUserType;
    private javax.swing.JTextField jUsername;
    private javax.swing.JPasswordField jUserpw;
    private javax.swing.JButton jbtnBack;
    // End of variables declaration//GEN-END:variables
}
