/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class View_Patient extends javax.swing.JFrame {

    /**
     * Creates new form View_Patient
     */
    public View_Patient() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpaid = new javax.swing.JTextField();
        jpaname = new javax.swing.JTextField();
        jwardid = new javax.swing.JTextField();
        jwardname = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jView = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel2.setText("Patient Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 138, -1, -1));

        jLabel3.setText("Ward ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 209, -1, -1));

        jLabel4.setText("Ward Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 280, -1, -1));

        jLabel5.setText("Status :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        jPanel1.add(jpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 180, -1));
        jPanel1.add(jpaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 180, -1));
        jPanel1.add(jwardid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 180, -1));
        jPanel1.add(jwardname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 180, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Discharged", "Not Dscharged" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 180, -1));

        jView.setText("View");
        jView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewActionPerformed(evt);
            }
        });
        jPanel1.add(jView, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 100, -1));

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });
        jPanel1.add(jReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/newemp.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewActionPerformed
   
        try {
            Statement stat= DBConnect.getStatemennt();
            ResultSet rs = stat.executeQuery("select patient_details.Patient_Id,patient_details.First_name,ward.Ward_id,ward.Ward_name from patient_details,ward where patient_details.Ward_id=ward.Ward_id");
            
            
            boolean type=false;
            while(rs.next()) {
                String paid = rs.getString(1);
                String  Name=rs.getString(2);
                String wardid=rs.getString(3);
                String wardname=rs.getString(4);
                System.out.println(Name);
                System.out.println(wardid);
                System.out.println(wardname);
                
               if(paid.equals(jpaid.getText())) 
               {
                   type = true;
                jpaname.setText(Name);
                jwardid.setText(wardid);
                jwardname.setText(wardname);
               }
              
            }
            if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning!There is no any patient in that No!","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
            
                 
            }
            
         catch (SQLException ex) {
            Logger.getLogger(View_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jViewActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        jpaid.setText(null);
        jpaname.setText(null); 
        jwardid.setText(null);
        jwardname.setText(null);
    }//GEN-LAST:event_jResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jReset;
    private javax.swing.JButton jView;
    private javax.swing.JTextField jpaid;
    private javax.swing.JTextField jpaname;
    private javax.swing.JTextField jwardid;
    private javax.swing.JTextField jwardname;
    // End of variables declaration//GEN-END:variables
}
