/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import Admin.Admin_Welcome;
import Doctor.Doctor_SearchPatient;
import Secure.DBConnect;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Ward_Management extends javax.swing.JFrame {

    /**
     * Creates new form Ward_Management
     */
    public Ward_Management() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jwardid = new javax.swing.JTextField();
        jwardname = new javax.swing.JTextField();
        jdateofjoined = new javax.swing.JTextField();
        jmax = new javax.swing.JTextField();
        jemp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jbtnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ward Managment");

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Ward  ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel3.setText("Ward Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel5.setText("Date of Started :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel6.setText("Max. Patients :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel7.setText("Employed Staff :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));
        jPanel1.add(jwardid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 210, -1));
        jPanel1.add(jwardname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 210, -1));
        jPanel1.add(jdateofjoined, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 210, -1));
        jPanel1.add(jmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 210, -1));
        jPanel1.add(jemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 210, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 110, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 110, 40));

        jbtnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jbtnUpdate.setText("Update");
        jbtnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 110, 40));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 100, 40));

        jbtnSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSearch.setText("Search");
        jbtnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Welcomeback1.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            stat.executeUpdate("INSERT INTO ward(Ward_id,Ward_name,Date_started,Max_patients,Employed_staff) VALUES('"+jwardid.getText()+"','"+jwardname.getText()+"','"+jdateofjoined.getText()+"','"+jmax.getText()+"','"+jemp.getText()+"')");
            JOptionPane.showMessageDialog(this,"Successfilly Added!","success!",JOptionPane.INFORMATION_MESSAGE); 

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
        jwardid.setText(null); 
        jwardname.setText(null);
        jdateofjoined.setText(null);
        jmax.setText(null);
        jemp.setText(null);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            stat.executeUpdate("UPDATE ward set Max_patients='" + jmax.getText() + "',Employed_staff='" + jemp.getText() + "' where Ward_id='" + jwardid.getText() + "'" );
            JOptionPane.showMessageDialog(this,"Successfilly Updated!","success!",JOptionPane.INFORMATION_MESSAGE); 

        } catch (SQLException ex) {
            Logger.getLogger(Ward_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Statement stat= DBConnect.getStatemennt();
            stat.executeUpdate("DELETE FROM ward where Ward_id='" + jwardid.getText() + "'");
        } catch (SQLException ex) {
            Logger.getLogger(Ward_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Admin_Welcome aw = new Admin_Welcome();
        aw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        if(jwardid.getText().equals(""))
      {
            JOptionPane.showMessageDialog(this,"Error! Empty Ward Id field","Unuccess!",JOptionPane.INFORMATION_MESSAGE);
            return;
            
      }
        try {
            Statement stat= DBConnect.getStatemennt();
            ResultSet rs1 = stat.executeQuery("SELECT 	Ward_id,Ward_name,Date_started,Max_patients,Employed_staff FROM ward WHERE Ward_id='" + jwardid.getText() + "'" );
            
            boolean type=false;
            while(rs1.next()) {
                String wardid = rs1.getString(1);
                String wardname = rs1.getString(2);
                String date_start=rs1.getString(3);
                String max_patient=rs1.getString(4);
                String employe_staff=rs1.getString(5);
                
                System.out.println(wardid);
                System.out.println(wardname);
                System.out.println(date_start);
                System.out.println(max_patient);
                System.out.println(employe_staff);
                
               
                
               if(wardid.equals(jwardid.getText())) 
               {
                   type = true;
                jwardname.setText(wardname);
                jdateofjoined.setText(date_start);
                jmax.setText(max_patient);
                jemp.setText(employe_staff);
               }
              
            }
            if(type==false)
            {
                
                 JOptionPane.showMessageDialog(this,"Warning! Wrong Ward Id!","Unsuccess!",JOptionPane.INFORMATION_MESSAGE);   
            }
        }
            catch (SQLException ex) {
            Logger.getLogger(Doctor_SearchPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jbtnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ward_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ward_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ward_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ward_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ward_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jdateofjoined;
    private javax.swing.JTextField jemp;
    private javax.swing.JTextField jmax;
    private javax.swing.JTextField jwardid;
    private javax.swing.JTextField jwardname;
    // End of variables declaration//GEN-END:variables
}
